#!/bin/sh

set -e

if [ "$1" = configure ]; then
  # Automatically added by dh_installinit
  (cd /usr/share/noipam && /usr/bin/npm install)

  if ! getent passwd _noipam > /dev/null; then
    adduser --system --quiet --home /nonexistent --no-create-home \
      --shell /bin/false --force-badname --group --gecos "NoIPAM User" _noipam
  fi

  if ! dpkg-statoverride --list /var/run/noipam >/dev/null 2>&1; then
    dpkg-statoverride --update --add _noipam _noipam 0755 /var/run/noipam
  fi

fi